name: Merge any release branch to master
on:
  push:
    branches:
      - 'release/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge branch2 -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          message: Merge staging into master
          github_token: ${{ secrets.GIT_TOKEN }}